version: '3.6'

services:
  detect-face-ui:
    container_name: detect-face-ui
    build: ./
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - '8000:80'
    command: "nginx -g 'daemon off;'"
